Input=C:/Users/reena/Desktop/JAVA_26/FileProcessingUtility/file/Input
Output=C:/Users/reena/Desktop/JAVA_26/FileProcessingUtility/file/Output
Reject=C:/Users/reena/Desktop/JAVA_26/FileProcessingUtility/file/Reject
Backup=C:/Users/reena/Desktop/JAVA_26/FileProcessingUtility/file/Backup